Sub compo()

'El codigo de pais se coloca en este campo'
Cells.Replace wHAT:="* THAILAND /", Replacement:=""
Cells.Replace wHAT:="* INDIA /", Replacement:=""
Cells.Replace wHAT:="* TURKEY /", Replacement:=""
Cells.Replace wHAT:="* CHINA /", Replacement:=""
Cells.Replace wHAT:="* VIETNAM /", Replacement:=""
Cells.Replace wHAT:="* INDONESIA /", Replacement:=""
Cells.Replace wHAT:="* CAMBODIA /", Replacement:=""
Cells.Replace wHAT:="* EGYPT /", Replacement:=""

'Cuando se va a hacer el borrado de elementos cortos, se pueden usar espacios para lograr borrados exactos'
Cells.Replace wHAT:="ID ", Replacement:=""
Cells.Replace wHAT:="TW ", Replacement:=""
Cells.Replace wHAT:="CN ", Replacement:=""
Cells.Replace wHAT:="VN ", Replacement:=""
Cells.Replace wHAT:="HK ", Replacement:=""
Cells.Replace wHAT:="LK ", Replacement:=""
Cells.Replace wHAT:="KH ", Replacement:=""
Cells.Replace wHAT:="PK ", Replacement:=""
Cells.Replace wHAT:="MX ", Replacement:=""
Cells.Replace wHAT:="MYA ", Replacement:=""

'Se puede colocar caracteres especiales como asteriscos, espacios, etc para que sea mas accurate el borrado'
Cells.Replace wHAT:="* CN", Replacement:=""
Cells.Replace wHAT:="* TR", Replacement:=""
Cells.Replace wHAT:="* TH", Replacement:=""
Cells.Replace wHAT:="* IN", Replacement:=""
Cells.Replace wHAT:="* MY", Replacement:=""
Cells.Replace wHAT:="* JO", Replacement:=""


'Reglas mas comunes encontradas para errores'
Cells.Replace wHAT:="COMP1", Replacement:="COMPOSICION"
Cells.Replace wHAT:="COMP2", Replacement:="COMPOSICION"
Cells.Replace wHAT:="ROP: ", Replacement:=""
Cells.Replace wHAT:="EXT ", Replacement:="EXTERIOR"
Cells.Replace wHAT:="T:", Replacement:="TEJIDO"
Cells.Replace wHAT:="CAPELLANA", Replacement:="CAPELLADA: "
Cells.Replace wHAT:="CAP ", Replacement:="CAPELLADA: "
Cells.Replace wHAT:="*CAP:", Replacement:="CAPELLADA: "
Cells.Replace What:="CAPA:", Replacement:="CAPELLADA: "
Cells.Replace wHAT:="C.", Replacement:="CAPELLADA:"
Cells.Replace wHAT:="C:", Replacement:="CAPELLADA:"
Cells.Replace wHAT:="F.", Replacement:="FORRO:"
Cells.Replace wHAT:="F:", Replacement:="FORRO:"
Cells.Replace wHAT:="S:", Replacement:="SUELA:"
Cells.Replace wHAT:="S.", Replacement:="SUELA:"
Cells.Replace wHAT:="CUE ", Replacement:="CUERO"
Cells.Replace wHAT:="FORR ", Replacement:="FORRO"
Cells.Replace wHAT:="TEXTILE", Replacement:="TEXTIL"
Cells.Replace wHAT:="TEXT ", Replacement:="TEXTIL"
Cells.Replace wHAT:="TEX ", Replacement:="TEXTIL"
Cells.Replace wHAT:="SINT", Replacement:="SINTETICO"
Cells.Replace wHAT:="SUE ", Replacement:="SUELA"
Cells.Replace wHAT:="CAU ", Replacement:="CAUCHO"
Cells.Replace wHAT:="PLAST ", Replacement:="PLASTICO"
Cells.Replace wHAT:="POLIE ", Replacement:="POLIESTER"
Cells.Replace wHAT:="ENSAM ", Replacement:="ENSAMBLAJE"
Cells.Replace wHAT:="PLANTI ", Replacement:="PLANTILLA"
Cells.Replace wHAT:="RYN", Replacement:="RAYON"
Cells.Replace wHAT:="CV", Replacement:="RAYON"
Cells.Replace wHAT:="%OTHER", Replacement:=""
Cells.Replace wHAT:="CONST ", Replacement:="CONSTITUCION"
Cells.Replace wHAT:="SPANDEX", Replacement:="ELASTENO"
Cells.Replace wHAT:="spand", Replacement:="ELASTENO"
Cells.Replace wHAT:="nylon", Replacement:="NYLON"
Cells.Replace wHAT:="FORRO: NINGUNO", Replacement:=" "
Cells.Replace wHAT:="FORRO: SIN FORRO", Replacement:=" "
Cells.Replace wHAT:="pegadocosido", Replacement:="PEGADO-COSIDO"
Cells.Replace wHAT:="vulcanizadocosido", Replacement:="VULZANIZADO-COSIDO"
Cells.Replace wHAT:="VULCANIZADO", Replacement:="VULCANIZADO"
Cells.Replace wHAT:="ÓRGANICO", Replacement:="ORGANICO"
Cells.Replace wHAT:="POLYESTER", Replacement:="POLIESTER"
Cells.Replace wHAT:="ELASTODIENE", Replacement:="ELASTENO"
Cells.Replace wHAT:="ELASTANE", Replacement:="ELASTENO"
Cells.Replace wHAT:="ELASTERELL P", Replacement:="ELASTENO"
Cells.Replace wHAT:="ELASTANO", Replacement:="ELASTENO"
Cells.Replace wHAT:="ALU ", Replacement:="ALUMINIO "
Cells.Replace wHAT:="ANTI MICROBIAL", Replacement:=" "
Cells.Replace wHAT:="/TEJIDO DE PUNTO", Replacement:=" "
Cells.Replace wHAT:="/TEJIDO PLANO", Replacement:=" "
Cells.Replace wHAT:="/TEJIDO PUNTO", Replacement:=" "
Cells.Replace wHAT:="/ TEJIDO DE PUNTO", Replacement:=" "
Cells.Replace wHAT:="/ TEJIDO PLANO", Replacement:=" "
Cells.Replace wHAT:="/ TEJIDO PUNTO", Replacement:=" "
Cells.Replace wHAT:="/ TEJIDO  PLANO", Replacement:=" "
Cells.Replace wHAT:="TEJIDO PUNTO", Replacement:=" "
Cells.Replace wHAT:="TEJIDO DE PUNTO", Replacement:=" "
Cells.Replace wHAT:="/ TEJIDO DE PLANO", Replacement:=" "
Cells.Replace wHAT:="CONSTEJIDO PEGADO-COSIDO", Replacement:=" "
Cells.Replace wHAT:="TEJIDO TÉCNICO DE PUNTO DOBLE ", Replacement:=""
Cells.Replace wHAT:="TEJIDO TÉCNICO DE PUNTO DOBLE ", Replacement:=""
Cells.Replace wHAT:="TEJIDO DE PUNTO SIMPLE ", Replacement:=""
Cells.Replace wHAT:="TEJIDO DE PUNTO SIMPLE ", Replacement:=""
Cells.Replace wHAT:="TEJIDO CALADO ", Replacement:=""
Cells.Replace wHAT:="TEJIDO JACQUARD ", Replacement:=""
Cells.Replace wHAT:="/TEXTIL PUNTO", Replacement:=""
Cells.Replace wHAT:="/ FORRO:", Replacement:=""
Cells.Replace wHAT:=" TEJIDO:PUNTO", Replacement:=""
Cells.Replace wHAT:="CUERO DE VACA", Replacement:="CUERO "
Cells.Replace wHAT:="CUERO VACUNO (TOP CUERO VACUNO)", Replacement:="CUERO "
Cells.Replace wHAT:="CUER VAC. (CUER SUP.)", Replacement:="CUERO "
Cells.Replace wHAT:="CUER. VAC (CUER SUP. DE VACA)", Replacement:="CUERO "
Cells.Replace wHAT:="CUERO VACUNO (CUERO SUPERIOR)", Replacement:="CUERO "
Cells.Replace wHAT:="CUERO VACUNO (CUERO SUPERIOR VACUNO)", Replacement:="CUERO "
Cells.Replace wHAT:=" POLIÉSTER TEJIDO", Replacement:="POLIESTER "
Cells.Replace wHAT:=", TEXTIL PUNTO", Replacement:=""
Cells.Replace wHAT:="/ TEXTIL PUNTO", Replacement:=""

'ERRORES EN INGLES'
Cells.Replace wHAT:="REC.PES", Replacement:="POLIESTER "
Cells.Replace wHAT:="REC. PES", Replacement:="POLIESTER "
Cells.Replace wHAT:="PES ", Replacement:="POLIESTER"
Cells.Replace wHAT:="PES/", Replacement:="POLIESTER "
Cells.Replace wHAT:="PES-", Replacement:="POLIESTER "
Cells.Replace wHAT:="RUBBER", Replacement:="CAUCHO"
Cells.Replace wHAT:="RU ", Replacement:="CAUCHO"
Cells.Replace wHAT:="POLYPROPYLENE", Replacement:="POLIPROPILENO"
Cells.Replace wHAT:="THERMOPLASTICOIC ELASTOMER", Replacement:="ELASTOMERO TERMOPLASTICO"
Cells.Replace wHAT:="THERMOPLASTICOIC ELASTOMER", Replacement:="ELASTOMERO TERMOPLASTICO"
Cells.Replace wHAT:="LOW DENSITY POLYETHYLENE", Replacement:="POLIETILENO"
Cells.Replace wHAT:="UPPER", Replacement:="CAPELLADA"
Cells.Replace wHAT:="LEATHER", Replacement:="CUERO"
Cells.Replace wHAT:="OUTSOLE", Replacement:="SUELA"
Cells.Replace wHAT:="COMBED COTTON", Replacement:="ALGODON "
Cells.Replace wHAT:="COTTON", Replacement:="ALGODON "
Cells.Replace wHAT:="CO/", Replacement:="ALGODON "
Cells.Replace wHAT:="CO-", Replacement:="ALGODON "
Cells.Replace wHAT:="POLIESTER PLANT", Replacement:="POLIESTER"
Cells.Replace wHAT:="ALGODON PLANT", Replacement:="ALGODON"
Cells.Replace wHAT:="ORGANIC CO", Replacement:="ALGODON ORGANICO"
Cells.Replace wHAT:="FORR", Replacement:="FORRO"
Cells.Replace wHAT:="ELASTERELLP", Replacement:="ELASTENO"
Cells.Replace wHAT:="COMPOSICION", Replacement:=""
Cells.Replace wHAT:="TEXTILE", Replacement:="TEXTIL"
Cells.Replace wHAT:="SYNTHETIC", Replacement:="SINTETICO"
Cells.Replace wHAT:="ETHYLENE-VINYL ACETATE (EVA)", Replacement:="EVA "
Cells.Replace wHAT:="MESH", Replacement:="MALLA"
Cells.Replace wHAT:="SOLE", Replacement:="SUELA"
Cells.Replace wHAT:="BODY:", Replacement:=""
Cells.Replace wHAT:="BODY: ", Replacement:=""
Cells.Replace wHAT:="BODY : ", Replacement:=""
Cells.Replace wHAT:="LINING", Replacement:="RECUBRIMIENTO "
Cells.Replace wHAT:="KNIT", Replacement:="TEJIDO "
Cells.Replace wHAT:="WOVEN", Replacement:="TEJIDO "
Cells.Replace wHAT:="SLEEVES", Replacement:="MANGAS"
Cells.Replace wHAT:="BODYSUIT", Replacement:=""
Cells.Replace wHAT:="-   ANTI PILLING - MECHANICAL TREATMENT", Replacement:=""
Cells.Replace wHAT:="-   PEACH BACK X 1 TIME   PEACH FACE X 1 TIME", Replacement:=""
Cells.Replace wHAT:="-HYDROPHILIC (MIDORI)", Replacement:=""
Cells.Replace wHAT:="-HYDROPHILIC FINISH", Replacement:=""
Cells.Replace wHAT:="-   PRINT - DIGITAL SUBLIMATION - DISPERSE", Replacement:=""
Cells.Replace wHAT:=" PRINT - ROLLER - PIGMENT   ANTI PILLING - ", Replacement:=""
Cells.Replace wHAT:="-FRENCH TERRY-ANTI PILLING - ENZYME TREATMENT", Replacement:=""
Cells.Replace wHAT:="-SINGLE JERSEY / ANTI MICROBIAL / ANTI UV", Replacement:=""
Cells.Replace wHAT:="Plain weave-coating - PU - clear", Replacement:=""
Cells.Replace wHAT:="Plain weave-coating - PU - clear / DWR - PFC Free", Replacement:=""
Cells.Replace wHAT:="PLAIN WEAVE / PRINT - DIGITAL SUBLIMATION - DISPERSE", Replacement:=""
Cells.Replace wHAT:="Plain weave", Replacement:=""
Cells.Replace wHAT:="-   PEACH - CARBON", Replacement:=""
Cells.Replace wHAT:="-BCAUCHOSHED BACK", Replacement:=""
Cells.Replace wHAT:="--SILICON FINISH ", Replacement:=""
Cells.Replace wHAT:="PU COATED ", Replacement:=""
Cells.Replace wHAT:="DOUBLEWEAVE-DWR - PFC FREE", Replacement:=""
Cells.Replace wHAT:="FLEECE", Replacement:="FORRO POLAR"
Cells.Replace wHAT:="SHELL", Replacement:="EXTERIOR"
Cells.Replace wHAT:="HYDROPHILIC FINISH", Replacement:=""
Cells.Replace wHAT:="SANDED BACK", Replacement:=""
Cells.Replace wHAT:="UPER", Replacement:="CAPELLADA: "
Cells.Replace wHAT:="MIDSOLE", Replacement:="MEDIASUELA: "
Cells.Replace wHAT:="SOCKLINER", Replacement:="PLANTILLA: "
Cells.Replace wHAT:="PALM", Replacement:="PALMA: "
Cells.Replace wHAT:=" OTHER", Replacement:=" OTRO: "
Cells.Replace wHAT:=" ETHYLENE VINYL ACETATE", Replacement:="EVA "
Cells.Replace wHAT:="POLYURETHANE", Replacement:="POLIURETANO"
Cells.Replace wHAT:="TEMP GLASS", Replacement:="VIDRIO TEMPLADO "
Cells.Replace wHAT:="AND", Replacement:="Y "
Cells.Replace wHAT:="TRICOT", Replacement:="TEJIDO "
Cells.Replace wHAT:="DOUBLETEJIDO", Replacement:=" "
Cells.Replace wHAT:="MOCK EYELET / ANTI UV", Replacement:=" "
Cells.Replace wHAT:="ANTI MICROBIAL", Replacement:=" "
Cells.Replace wHAT:="BRUSHED BACK", Replacement:=" "
Cells.Replace wHAT:="ENGINEERED", Replacement:=" "
Cells.Replace wHAT:="SILICON FINISH / ENZYME FINISH", Replacement:=" "
Cells.Replace wHAT:="ENZYME FINISH", Replacement:=" "
Cells.Replace wHAT:="SINGLE JERSEY- ", Replacement:=" "
Cells.Replace wHAT:="SINGLE JERSEY", Replacement:=" "
Cells.Replace wHAT:="-PEACH - CARBON", Replacement:=" "
Cells.Replace wHAT:="Lamination", Replacement:=" "
Cells.Replace wHAT:="Dobby", Replacement:=" "
Cells.Replace wHAT:="PLAITED-", Replacement:=" "
Cells.Replace wHAT:="PIQUE", Replacement:="TEJIDO "
Cells.Replace wHAT:="/ ANTI UV", Replacement:=" "
Cells.Replace wHAT:="POLYVINYLCHLORIDE", Replacement:="PVC "




'Correcciones de errores generados por la macro
Cells.Replace wHAT:="REC.POLIESTER ", Replacement:="POLIESTER "
Cells.Replace wHAT:="SINTETICOETICO", Replacement:="SINTETICO"
Cells.Replace wHAT:="SINTETICOENTICO", Replacement:="SINTETICO"
Cells.Replace wHAT:="SINTETICOÉTICO", Replacement:="SINTETICO"
Cells.Replace wHAT:="CUERORO", Replacement:="CUERO"
Cells.Replace wHAT:="CAUCHOCHO", Replacement:="CAUCHO"
Cells.Replace wHAT:="TEXTILIL", Replacement:="TEXTIL"
Cells.Replace wHAT:="TEXTILTILIL", Replacement:="TEXTIL"
Cells.Replace wHAT:="LATEXTIL", Replacement:="LATEX"
Cells.Replace wHAT:="CUERORPO", Replacement:="CUERPO"
Cells.Replace wHAT:="POLIESTERSTER", Replacement:="POLIESTER"
Cells.Replace wHAT:="PLASTICOICO", Replacement:="PLASTICO"
Cells.Replace wHAT:="SUELATER", Replacement:="SUETER"
Cells.Replace wHAT:="CAPELLADAELLDA", Replacement:="CAPELLADA"
Cells.Replace wHAT:="RECAPELLADA", Replacement:="CAPELLADA"
Cells.Replace wHAT:="CAPELLADAELLADA", Replacement:="CAPELLADA"
Cells.Replace wHAT:="CAPELLADAELLADA:", Replacement:="CAPELLADA"
Cells.Replace wHAT:="SUELALA", Replacement:="SUELA"
Cells.Replace wHAT:="PLANTILLALLA", Replacement:="PLANTILLA"
Cells.Replace wHAT:="ENSAMBLAJEBLE", Replacement:="ENSAMBLAJE"
Cells.Replace wHAT:="ENSAMBLAJEBLAJE", Replacement:="ENSAMBLAJE"
Cells.Replace wHAT:="COMPOSICIONOSICION", Replacement:="COMPOSICION"
Cells.Replace wHAT:="POLIESTEXTILR", Replacement:="POLIESTER"
Cells.Replace wHAT:="POLIÉSTEXTILR", Replacement:="POLIESTER"
Cells.Replace wHAT:="POLYESTEXTILR", Replacement:="POLIESTER"
Cells.Replace wHAT:="CONSTITUCIONEJIDO", Replacement:="CONSTITUCION"
Cells.Replace wHAT:="TEXTILTILERIOR", Replacement:="TEXTIL"
Cells.Replace wHAT:="PLASTICOIC", Replacement:="PLASTICO"
Cells.Replace wHAT:="TCUERO SINTETICO", Replacement:="TPU"
Cells.Replace wHAT:="FORROO", Replacement:="FORRO"
Cells.Replace wHAT:="SINTETICOETICA", Replacement:="SINTETICO"
Cells.Replace wHAT:="WIPOLIESTERINDVIDUALES", Replacement:="WIPES "
Cells.Replace wHAT:="WIPOLIESTER", Replacement:="WIPES "

'correcciones finales'
Cells.Replace wHAT:="TEJIDO:", Replacement:=""
Cells.Replace wHAT:="TEJIDO", Replacement:=""
Cells.Replace wHAT:="EXTERIOR", Replacement:=""
Cells.Replace wHAT:=" PLANO", Replacement:=""
Cells.Replace wHAT:=" LISO", Replacement:=""
Cells.Replace wHAT:=" TEXTIL", Replacement:=""

Cells.Replace wHAT:="ALGODÓN", Replacement:="ALGODON"
Cells.Replace wHAT:="POLÍESTER", Replacement:="POLIESTER"
Cells.Replace wHAT:="POLIÉSTER", Replacement:="POLIESTER"
Cells.Replace wHAT:="SINTÉTICO", Replacement:="SINTETICO"


'Esta siempre es la ultima rutina'
'Cells.Replace wHAT:="/ ", Replacement:=" "'
'PU-CUERO, PA-NYLON, EL-ELASTANO'


End Sub

