Sub model()

'Reglas con dos letras'
Cells.Replace What:="Hd ", Replacement:="Hoodie "
Cells.Replace What:="3S ", Replacement:="3-Stripes "
Cells.Replace What:="3s ", Replacement:="3-Stripes "
Cells.Replace What:="Pt ", Replacement:="Pant "
Cells.Replace What:="Pnt ", Replacement:="Pant "
Cells.Replace What:="Ru ", Replacement:="Running "
Cells.Replace What:="Cr ", Replacement:="Crew "
Cells.Replace What:="Sb ", Replacement:="Shoe Bag "
Cells.Replace What:="Wb ", Replacement:="Windbreaker "
Cells.Replace What:="Tr ", Replacement:="Tric "
Cells.Replace What:="Tk ", Replacement:="Track "
Cells.Replace What:="Bl ", Replacement:="Big logo "
Cells.Replace What:="Bp ", Replacement:="Backpack "
Cells.Replace What:="Pb ", Replacement:="Primeblue "
Cells.Replace What:="Kt ", Replacement:="Kit "
Cells.Replace What:="Fr ", Replacement:="Feelready "
Cells.Replace What:="Lg ", Replacement:="Logo "
Cells.Replace What:="Mm ", Replacement:="Mickey Mouse "
Cells.Replace What:="Hc ", Replacement:="Half cushioned "
Cells.Replace What:="Tf ", Replacement:="Turf  "
Cells.Replace What:="Vt ", Replacement:="Vertical "
Cells.Replace What:="Gr ", Replacement:="Graphic "
Cells.Replace What:="Sl ", Replacement:="Sleeve "
Cells.Replace What:="Sle ", Replacement:="Sleeve "
Cells.Replace What:="Re ", Replacement:=""
Cells.Replace What:="Ua ", Replacement:=""
Cells.Replace What:="Wr ", Replacement:=""
Cells.Replace What:="Wv ", Replacement:=""
Cells.Replace What:="Wvn ", Replacement:=""
Cells.Replace What:="We ", Replacement:=""
Cells.Replace What:=" Bp ", Replacement:="Backpack"

'equivalencia de nombres completos'
Cells.Replace What:="Fi ", Replacement:="Future Icons  "
Cells.Replace What:="Cp ", Replacement:="Comfy Princesses "
Cells.Replace What:="Fg ", Replacement:="Firm Ground "
Cells.Replace What:="Fb ", Replacement:="Fellbrilliant "
Cells.Replace What:="SS ", Replacement:="Short Sleeve "
Cells.Replace What:="Aop", Replacement:="All Over Print "
Cells.Replace What:="Tsr ", Replacement:="Techstyle running"
Cells.Replace What:="kfp", Replacement:="kung fu panda "
Cells.Replace What:="Kfp", Replacement:="kung fu panda "
Cells.Replace What:="Pntspl", Replacement:="Paint Splatter "
Cells.Replace What:="Ptspl", Replacement:="Paint Splatter "




'Reglas con tres letras o mas'
Cells.Replace What:="Jkt ", Replacement:="Jacket "
Cells.Replace What:=" Clb", Replacement:="Club"
Cells.Replace What:="Pred ", Replacement:="Predator "
Cells.Replace What:="Stu ", Replacement:="Studio "
Cells.Replace What:="Snapba ", Replacement:="Snapback "
Cells.Replace What:="Sho ", Replacement:="Short "
Cells.Replace What:="Emb ", Replacement:="Embroidered "
Cells.Replace What:="Snst ", Replacement:="Sunset "
Cells.Replace What:="Vcyrdy ", Replacement:="Vacation Ready "
Cells.Replace What:="Brshstrk ", Replacement:="Brushstroke "
Cells.Replace What:="3Pp ", Replacement:="3 per pack "
Cells.Replace What:="3pp ", Replacement:="3 per pack "
Cells.Replace What:="Cro ", Replacement:="Cropped "
Cells.Replace What:="Tig ", Replacement:="Tight "
Cells.Replace What:="Jsy ", Replacement:="Jersey "
Cells.Replace What:="D2M ", Replacement:="Designed 2 Move "
Cells.Replace What:="Jsy ", Replacement:="Jersey "
Cells.Replace What:="Tre ", Replacement:="Trefolio "
Cells.Replace What:="Baseb ", Replacement:="Baseball "
Cells.Replace What:="BBall ", Replacement:="Baseball "
Cells.Replace What:="Clm ", Replacement:="Climate "
Cells.Replace What:="Clm ", Replacement:="Climate "
Cells.Replace What:="Perf ", Replacement:="Performance "
Cells.Replace What:="Bttl ", Replacement:="Bottle "
Cells.Replace What:="Btl ", Replacement:="Bottle "
Cells.Replace What:="Sck ", Replacement:="Socks "
Cells.Replace What:="Crw ", Replacement:="Crew "
Cells.Replace What:="Sum ", Replacement:="Summer "
Cells.Replace What:="Inf ", Replacement:="Infant "
Cells.Replace What:="Prd ", Replacement:="Pride "
Cells.Replace What:="Str ", Replacement:="Stripe "
Cells.Replace What:="Camo ", Replacement:="Camuflaje  "
Cells.Replace What:="Hyprchrg ", Replacement:="Hypercharge  "
Cells.Replace What:="Wns", Replacement:=""
Cells.Replace What:="Ess+ ", Replacement:="Essentials + "
Cells.Replace What:="ESS ", Replacement:="Essential "
Cells.Replace What:="Essntl ", Replacement:="Essential "
Cells.Replace What:="WOR ", Replacement:="Essential "
Cells.Replace What:="HI2 ", Replacement:="High 2 "
Cells.Replace What:="Fnl ", Replacement:="Funnel "
Cells.Replace What:="Flc", Replacement:="Fleece "
Cells.Replace What:="Jkt", Replacement:="Jacket "
Cells.Replace What:="bkn", Replacement:="Brooklyn"
Cells.Replace What:="Mns ", Replacement:=""
Cells.Replace What:="Fitnss", Replacement:="Fitness "
Cells.Replace What:="Fitn", Replacement:="Fitness "
Cells.Replace What:="nkct ", Replacement:=""
Cells.Replace What:="nsw ", Replacement:=""
Cells.Replace What:="Nsw ", Replacement:=""
Cells.Replace What:="Ssnl ", Replacement:=""
Cells.Replace What:="Pantalon corto ", Replacement:=""
Cells.Replace What:="Pantalon Largo ", Replacement:=""
Cells.Replace What:="Pantalon de chandal ", Replacement:=""
Cells.Replace What:="Men'S ", Replacement:=""
Cells.Replace What:="Women's ", Replacement:=""
Cells.Replace What:="Boy's ", Replacement:=""
Cells.Replace What:="Girl's ", Replacement:=""
Cells.Replace What:="Men", Replacement:=""
Cells.Replace What:="Women", Replacement:=""
Cells.Replace What:="Boy", Replacement:=""
Cells.Replace What:="Girl", Replacement:=""
Cells.Replace What:="Swsh", Replacement:=""
Cells.Replace What:="M Nk ", Replacement:=""
Cells.Replace What:="Nsw ", Replacement:=""
Cells.Replace What:="Pjt  ", Replacement:="Project "
Cells.Replace What:="Swtpants ", Replacement:="Sweatpants "
Cells.Replace What:="/c De Hombre", Replacement:=""
Cells.Replace What:="Fg/Mg", Replacement:=""
Cells.Replace What:="Fg/Ag", Replacement:=""
Cells.Replace What:="Fg/ag", Replacement:=""
Cells.Replace What:="/ Glw.", Replacement:=""
Cells.Replace What:="/ Gl1.", Replacement:=""
Cells.Replace What:="/ Sh.", Replacement:=""
Cells.Replace What:="/ C12", Replacement:=""
Cells.Replace What:="/ B12", Replacement:=""
Cells.Replace What:="/ D12", Replacement:=""
Cells.Replace What:="7/8 Leg Ns", Replacement:=""
Cells.Replace What:="7/8 Legg", Replacement:=""
Cells.Replace What:="7/8Leg Ns", Replacement:=""
Cells.Replace What:="3p / U", Replacement:=""
Cells.Replace What:="/ Sl", Replacement:=""
Cells.Replace What:="B / Kd", Replacement:=""
Cells.Replace What:="W / Sm", Replacement:=""
Cells.Replace What:="7/8 Tight", Replacement:=""
Cells.Replace What:="/ L12.", Replacement:=""

Cells.Replace What:="Jrsy", Replacement:="Jersey "
Cells.Replace What:="Tgt", Replacement:="Tight "
Cells.Replace What:="Sck", Replacement:="Socks "
Cells.Replace What:="Woven ", Replacement:=""
Cells.Replace What:="U Nk ", Replacement:=""
Cells.Replace What:="Y Nk ", Replacement:=""
Cells.Replace What:="B Nk ", Replacement:=""
Cells.Replace What:="G Nk ", Replacement:=""
Cells.Replace What:="Nkg ", Replacement:=""
Cells.Replace What:="Nkb ", Replacement:=""
Cells.Replace What:="Nkct ", Replacement:=""
Cells.Replace What:="De Nino", Replacement:=""
Cells.Replace What:="De Hombre", Replacement:=""
Cells.Replace What:="Mtc", Replacement:="Match"
Cells.Replace What:="Mcs", Replacement:="Mercedes"
Cells.Replace What:="Hbr", Replacement:=""
Cells.Replace What:=" Mg", Replacement:=""
Cells.Replace What:="Nike", Replacement:=""
Cells.Replace What:="WNike", Replacement:=""
 




'imperfecciones a corregir'
Cells.Replace What:="Essential entials", Replacement:="Essential "
Cells.Replace What:="Essential ential", Replacement:="Essential "
Cells.Replace What:="TeAeromotion", Replacement:="Team "
Cells.Replace What:="CloudfoAeromotion", Replacement:="Cloudfoam "
Cells.Replace What:="CourtjAeromotion", Replacement:="Courtjam "
Cells.Replace What:="SlePant", Replacement:="Slept "
Cells.Replace What:="AdaPant", Replacement:="Adapt "
Cells.Replace What:="ADisruPant", Replacement:="Disrupt "
Cells.Replace What:="ScriPant", Replacement:="Script "
Cells.Replace What:="CloudfoAeromotion", Replacement:="Cloudfoam "

Cells.Replace What:=" W", Replacement:=""
Cells.Replace What:="arriors", Replacement:="Warriors "
Cells.Replace What:="indrunner", Replacement:="Windrunner "
Cells.Replace What:=" indrunner", Replacement:="Windrunner "
Cells.Replace What:=" ind", Replacement:="Wind "
Cells.Replace What:=" ing", Replacement:="Wing "
Cells.Replace What:=" itness", Replacement:="Witness "
Cells.Replace What:="ild", Replacement:=" Wild "
Cells.Replace What:="inflo", Replacement:="Winflow "
Cells.Replace What:="WWinflo", Replacement:="Winflow "
Cells.Replace What:=" ash", Replacement:="Wash "
Cells.Replace What:=" arm", Replacement:="Warm "
Cells.Replace What:=" in", Replacement:="Win "
Cells.Replace What:=" ater", Replacement:="Water "
Cells.Replace What:=" ordmark", Replacement:="Wordmark "
Cells.Replace What:=" hite", Replacement:="White "
Cells.Replace What:=" orkout", Replacement:="Workout "
Cells.Replace What:=" ave", Replacement:="Wave "
Cells.Replace What:=" aistbag", Replacement:="Wasitbag "
Cells.Replace What:=" ater", Replacement:="Water "
Cells.Replace What:=" aistpack", Replacement:="Waistpack "
Cells.Replace What:=" yland", Replacement:="Wyland "
Cells.Replace What:=" allet", Replacement:="Wallet "
Cells.Replace What:="Windy", Replacement:="Indy "
Cells.Replace What:="Wind y", Replacement:="Indy "

Cells.Replace What:="LiFrench Terry", Replacement:=" Lift "
Cells.Replace What:="ShiFrench Terry", Replacement:=" Shirft "
Cells.Replace What:="SWiFrench Terry", Replacement:=" Swift "
Cells.Replace What:="SeamleShortsleeve", Replacement:="Seamless "
Cells.Replace What:="Wind y", Replacement:="Indy "





Cells.Replace What:=" SS", Replacement:=""

'NO RESUELTOS :ess-Essentials , dy.disney, te:tappered, ps-pyrostorm, wo-women, am-aeromotion, Cre-crew, flo-flow,  lo-low'  
'rene-renew, bm-bmw, Ss-short sleeve'



End Sub
